# Generated by Django 5.1.6 on 2025-02-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='info',
            field=models.TextField(default='No additional info'),
        ),
    ]
